### ISSUE TITLE
Does not work with WooCommerce Subscription 2+

### ISSUE THREAD

**Issue by Dragelykke** [ePay/woocommerce#11] opened 2016-02-01 23:21 UTC
Does not work with WooCommerce Subscription 2+

**Comment by stefanmf** [comment] 2016-02-02 08:24
Duplicate of issue #9

**Comment by sorenla** [comment] 2016-11-21 10:46
Hello Dragelykke

This should be fixed in the [latest release](https://github.com/ePay/woocommerce/releases/latest).

**Closed by sorenla** 2016-11-21 10:46 UTC
