### ISSUE TITLE
Please wait window not redirecting

### ISSUE THREAD

**Issue by carcarefreaks** [ePay/woocommerce#53] opened 2020-11-16 20:30 UTC
Hi,
Recently we have been getting more and more complains from customers on IOS devices using Safari.
When they come to the last page before payment, that is suppose to redirect to payment window, it just hangs.
They can then come back at a later point and on the same device successfully complete the transaction.

On friday we had 2 customers in store completing an order at the same time, on identical devices, 1 could complete it, the other one hanged.

Attached is from a session with the issue, captured with mouseflow.

Could this be a backend problem at epay? or is it the plugin?

![2020-11-15 16 18 01](https://user-images.githubusercontent.com/33432065/99304426-a411ee80-2852-11eb-82b3-2c855fb185c3.jpg)

**Comment by AllanWLie** [comment] 2020-11-17 08:58
Hi @carcarefreaks 

Thank you for reporting this. Currently we do not have any other reporting this issue and we are unable to reproduce it based on the information you have provided. (iOS version / Safari version / phone model)

If it happens again please send an export / screenshot of the "Developer Console" (Know it is hard on a mobile device) and / or the module log (shortcut under the module configuration page) to support@bambora.com 

Thank you and have a good day.

Best regards
Allan Lie - Bambora Online A/S

**Comment by carcarefreaks** [comment] 2020-11-17 09:29
We have an ongoing case with Bambora support also about this issue.
We have 20-30 rapported incidents in the last 14 days, so quite serious.

We cannot reproduce the error our self either, and it is not all devices that experience this.

We have today send 5 incidents that we have caught in mouseflow to support, and hopefully it will bring us closer to a solution.

For us it could sound like the issue is on one of the bambora servers and not in the plugin it self, as the customer can get the error and then come back some hours later and complete the transaction without any issues.

Unless customers report this, other stores will not know that this happens.
Out of the 5 we have caught on Mouseflow, none of them reported the issue, but properly just used their money in another store.

**Comment by sessan** [comment] 2021-05-05 17:46
@carcarefreaks We have not heard more about this and most likely it is not plugin related therefore I'm closing this. If you continue to experience this issue please contact [support@bambora.com ](url) again. 

Best regards
Jessica - Bambora

**Closed by sessan** 2021-05-05 17:46 UTC
